import { Reveal } from '@/components/ui/Reveal'
import { AI_DEMO_ROWS } from '@/data/landing'

const ArrowIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M5 12h14M13 6l6 6-6 6" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
)

export function AIUnderstandingSection() {
  return (
    <section className="ai-sec" id="understand">
      <div className="wrap">
        <Reveal className="sec-head">
          <span className="eyebrow">The understanding layer</span>
          <h2 className="sect" style={{ marginTop: 18 }}>It reads commits like a teammate, not a parser.</h2>
          <p className="sub">A real release is mostly noise. The value isn't reformatting it — it's deciding what's worth saying, then saying it like a human. Here's the same five commits, understood:</p>
        </Reveal>
        <Reveal>
          <div className="demo">
            {AI_DEMO_ROWS.map(({ input, pill, pillClass, output, internal }) => (
              <div key={input} className={`xrow${internal ? ' internal' : ''}`}>
                <div className="in">
                  <span className="src">commit</span>
                  {input}
                </div>
                <div className="mid"><ArrowIcon /></div>
                <div className="out">
                  <span className={`pill ${pillClass}`}>{pill}</span>
                  <span className="txt">{output}</span>
                </div>
              </div>
            ))}
          </div>
        </Reveal>
        <Reveal>
          <div className="ai-note">
            <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8">
              <path d="M12 16v-4M12 8h.01" strokeLinecap="round" />
              <circle cx="12" cy="12" r="9" />
            </svg>
            <p>
              <b>This is the part GitHub can't do.</b> Autogenerated notes will faithfully print "refactor: extract auth middleware" to your users. ReleaseHub knows that line is noise, that the Node bump is a breaking change worth flagging, and that "race condition" should read like a sentence a customer would actually understand.
            </p>
          </div>
        </Reveal>
      </div>
    </section>
  )
}
