import { Reveal } from '@/components/ui/Reveal'
import { COMPARISON_ROWS } from '@/data/landing'

export function VSGitHubSection() {
  return (
    <section className="vs-sec" id="vs">
      <div className="wrap">
        <Reveal className="sec-head">
          <span className="eyebrow">The honest comparison</span>
          <h2 className="sect" style={{ marginTop: 18 }}>"GitHub already does release notes." Here's the actual difference.</h2>
          <p className="sub">GitHub's autogenerated notes are great at one thing: listing what merged. That's the start of the job, not the end of it.</p>
        </Reveal>
        <Reveal>
          <div className="vstable">
            <div className="vsrow vshead">
              <div className="vscell q">Capability</div>
              <div className="vscell gh">GitHub auto notes</div>
              <div className="vscell rh">ReleaseHub</div>
            </div>
            {COMPARISON_ROWS.map(({ capability, github, githubIcon, rh, rhIcon }) => (
              <div key={capability} className="vsrow">
                <div className="vscell q">{capability}</div>
                <div className="vscell gh"><span className="ic">{githubIcon}</span> {github}</div>
                <div className="vscell rh"><span className="ic">{rhIcon}</span> {rh}</div>
              </div>
            ))}
          </div>
        </Reveal>
        <Reveal>
          <p className="vs-foot">
            <b>Why a team switches:</b> GitHub answers "what changed?" for people who can read a repo. ReleaseHub answers "why should you care?" for everyone who can't — and saves the manual rewrite-and-paste loop every release. If your release notes already reach customers and stay readable, you don't need this. Most don't.
          </p>
        </Reveal>
      </div>
    </section>
  )
}
